"""PROTOTYPE — throwaway. Sample Trade data for the LLM-export shape question (#11).

Three Trades, chosen to stress the export rather than flatter it:

  1. AAOI  (US)  — clean winner, two partials then a trail exit. Adherence ~ nominal.
  2. NVDA  (US)  — stopped out before the partial band. Every counterfactual field
                   must come back `not_applicable`, not zero.
  3. BREN  (IDX) — reconstructed stop, insufficient history (recent listing), one
                   exit. Nulls and provenance caveats everywhere.

Values are plausible, not real. The point is the *shape*, not the numbers.
"""

TRADES = [
    {
        # --- identity -------------------------------------------------
        "trade_id": "us-aaoi-20260420",
        "book": "US",
        "currency": "USD",
        "symbol": "AAOI",
        "entry_date": "2026-04-20",
        "final_exit_date": "2026-05-15",
        "state": "frozen",
        "days_held": 19,
        # --- hand-entered ---------------------------------------------
        "setup": "base_breakout",
        "stop": 22.40,
        "stop_provenance": "recorded",
        # --- execution ------------------------------------------------
        "entry_avg_price": 24.86,
        "exit_avg_price": 31.02,
        "quantity": 1200,
        "exit_close": 30.74,  # C_x
        "equity_at_entry": 412_000.0,
        "risk_percentage": 0.72,
        "exposure_percentage": 7.24,
        "realized_r": 2.50,
        "realized_pct": 24.78,
        "realized_pnl": 7392.0,
        # --- volatility base ------------------------------------------
        "adr_pct": 4.62,
        # --- setup geometry, as-of prior close ------------------------
        "prior_close": 24.11,
        "ma_10": 22.85,
        "ma_20": 21.94,
        "ma_50": 20.12,
        "ma_100": 18.77,
        "ma_200": 17.40,
        "ma_dist_10": 1.18,
        "ma_dist_20": 1.90,
        "ma_dist_50": 3.58,
        "ma_dist_100": 4.79,
        "ma_dist_200": 5.99,
        "stack_state": "aligned_up",
        "prior_move_21d": 18.40,
        "prior_move_63d": 41.20,
        "prior_move_126d": 63.80,
        "pct_off_52w_high": -3.10,
        "rs_63d": 29.60,
        "volume_ratio": 3.10,
        "avg_turnover_20d": 41_200_000.0,
        # --- chase ----------------------------------------------------
        "stop_distance_adr": 2.14,
        "chased": True,
        # --- regime, referenced from RegimeSnapshot(book, date) -------
        "regime_at_entry": "strong_uptrend",
        "regime_at_exit": "uptrend",
        "benchmark": "QQQ",
        # --- exit geometry, as-of exit close --------------------------
        "adr_pct_at_exit": 5.10,
        "ma_dist_10_at_exit": 1.44,
        "ma_dist_20_at_exit": 2.71,
        "ma_dist_50_at_exit": 5.02,
        "ma_dist_100_at_exit": 6.88,
        "ma_dist_200_at_exit": 8.31,
        "stack_state_at_exit": "aligned_up",
        "rs_63d_at_exit": 34.10,
        # --- excursion, Trade level -----------------------------------
        "mfe_high": 33.80,
        "mfe_date": "2026-05-12",
        "mae_low": 23.90,
        "mae_date": "2026-04-21",
        # --- post-exit counterfactual ---------------------------------
        "fwd_return_20d": -8.20,
        "fwd_close_20d": 28.22,
        "fwd_high": 32.10,
        "fwd_high_date": "2026-05-19",
        "fwd_low": 27.05,
        "fwd_low_date": "2026-06-09",
        # --- exits ----------------------------------------------------
        "exits": [
            {
                "date": "2026-04-23",
                "quantity": 400,
                "price": 28.10,
                "reason": "scheduled_partial",
                "mfe_high": 28.90,
                "mfe_date": "2026-04-23",
                "mae_low": 23.90,
                "mae_date": "2026-04-21",
            },
            {
                "date": "2026-05-06",
                "quantity": 300,
                "price": 30.40,
                "reason": "discretionary_trim",
                "mfe_high": 31.60,
                "mfe_date": "2026-05-05",
                "mae_low": 23.90,
                "mae_date": "2026-04-21",
            },
            {
                "date": "2026-05-15",
                "quantity": 500,
                "price": 33.02,
                "reason": "close_below_ma10",
                "mfe_high": 33.80,
                "mfe_date": "2026-05-12",
                "mae_low": 23.90,
                "mae_date": "2026-04-21",
            },
        ],
        # --- adherence, ruleset v1 ------------------------------------
        "ruleset_version": "v1",
        "nominal_variant": "trail_ma10__partial_day3",
        "partial_state": "taken_in_band",
        "partial_timing_delta": 0,
        "trail_exit_delta": 0,
        "deviation_cost_price": 0.0,
        "best_fit_variant": "trail_ma10__partial_day3",
        "variants": [
            {"variant": "trail_ma10__partial_day3", "outcome": "resolved", "exit_price": 31.02, "r": 2.50, "fit_distance_days": 0},
            {"variant": "trail_ma10__partial_day5", "outcome": "resolved", "exit_price": 31.40, "r": 2.65, "fit_distance_days": 2},
            {"variant": "trail_ma10__partial_none", "outcome": "resolved", "exit_price": 32.02, "r": 2.90, "fit_distance_days": 3},
            {"variant": "trail_ma20__partial_day3", "outcome": "resolved", "exit_price": 29.80, "r": 2.00, "fit_distance_days": 6},
            {"variant": "trail_ma20__partial_day5", "outcome": "resolved", "exit_price": 30.10, "r": 2.12, "fit_distance_days": 7},
            {"variant": "trail_ma20__partial_none", "outcome": "resolved", "exit_price": 30.40, "r": 2.25, "fit_distance_days": 8},
        ],
        # --- qualitative ----------------------------------------------
        "exit_note": "Trailed it properly for once. Nearly trimmed the last third on the 12th when it went vertical — glad I didn't, the MA10 close came three days later.",
        # --- provenance ------------------------------------------------
        "bar_source": "yfinance",
        "fetch_date": "2026-06-10",
        "drift": None,
    },
    {
        "trade_id": "us-nvda-20260602",
        "book": "US",
        "currency": "USD",
        "symbol": "NVDA",
        "entry_date": "2026-06-02",
        "final_exit_date": "2026-06-03",
        "state": "frozen",
        "days_held": 2,
        "setup": "high_tight_flag",
        "stop": 168.00,
        "stop_provenance": "recorded",
        "entry_avg_price": 174.30,
        "exit_avg_price": 167.42,
        "quantity": 600,
        "exit_close": 166.90,
        "equity_at_entry": 418_500.0,
        "risk_percentage": 0.90,
        "exposure_percentage": 24.99,
        "realized_r": -1.09,
        "realized_pct": -3.95,
        "realized_pnl": -4128.0,
        "adr_pct": 2.90,
        "prior_close": 172.10,
        "ma_10": 168.40,
        "ma_20": 165.20,
        "ma_50": 158.90,
        "ma_100": 149.30,
        "ma_200": 138.70,
        "ma_dist_10": 0.74,
        "ma_dist_20": 1.38,
        "ma_dist_50": 2.64,
        "ma_dist_100": 4.56,
        "ma_dist_200": 6.68,
        "stack_state": "aligned_up",
        "prior_move_21d": 9.80,
        "prior_move_63d": 22.40,
        "prior_move_126d": 31.10,
        "pct_off_52w_high": -1.20,
        "rs_63d": 11.80,
        "volume_ratio": 1.40,
        "avg_turnover_20d": 8_940_000_000.0,
        "stop_distance_adr": 1.25,
        "chased": True,
        "regime_at_entry": "uptrend",
        "regime_at_exit": "uptrend",
        "benchmark": "QQQ",
        "adr_pct_at_exit": 3.20,
        "ma_dist_10_at_exit": -0.31,
        "ma_dist_20_at_exit": 0.36,
        "ma_dist_50_at_exit": 1.62,
        "ma_dist_100_at_exit": 3.71,
        "ma_dist_200_at_exit": 6.35,
        "stack_state_at_exit": "aligned_up",
        "rs_63d_at_exit": 10.90,
        "mfe_high": 176.20,
        "mfe_date": "2026-06-02",
        "mae_low": 166.10,
        "mae_date": "2026-06-03",
        "fwd_return_20d": 14.60,
        "fwd_close_20d": 191.27,
        "fwd_high": 194.40,
        "fwd_high_date": "2026-06-30",
        "fwd_low": 164.80,
        "fwd_low_date": "2026-06-04",
        "exits": [
            {
                "date": "2026-06-03",
                "quantity": 600,
                "price": 167.42,
                "reason": "stop_hit",
                "mfe_high": 176.20,
                "mfe_date": "2026-06-02",
                "mae_low": 166.10,
                "mae_date": "2026-06-03",
            }
        ],
        "ruleset_version": "v1",
        "nominal_variant": "trail_ma10__partial_day3",
        "partial_state": "not_applicable",
        "partial_timing_delta": None,
        "trail_exit_delta": None,
        "deviation_cost_price": None,
        "best_fit_variant": None,
        "variants": [
            {"variant": v, "outcome": "resolved", "exit_price": 167.42, "r": -1.09, "fit_distance_days": 0}
            for v in (
                "trail_ma10__partial_day3",
                "trail_ma10__partial_day5",
                "trail_ma10__partial_none",
                "trail_ma20__partial_day3",
                "trail_ma20__partial_day5",
                "trail_ma20__partial_none",
            )
        ],
        "exit_note": "Bought the flag on day two of the pullback instead of waiting for the range to tighten. Stop was under the low, it just went.",
        "bar_source": "yfinance",
        "fetch_date": "2026-07-02",
        "drift": None,
    },
    {
        "trade_id": "idx-bren-20260707",
        "book": "IDX",
        "currency": "IDR",
        "symbol": "BREN.JK",
        "entry_date": "2026-07-07",
        "final_exit_date": "2026-07-24",
        "state": "enriched",
        "days_held": 14,
        "setup": "other",
        "stop": 6900.0,
        "stop_provenance": "reconstructed",
        "entry_avg_price": 7240.0,
        "exit_avg_price": 7815.0,
        "quantity": 40_000,
        "exit_close": 7750.0,
        "equity_at_entry": 1_850_000_000.0,
        "risk_percentage": 0.74,
        "exposure_percentage": 15.65,
        "realized_r": 1.69,
        "realized_pct": 7.94,
        "realized_pnl": 23_000_000.0,
        "adr_pct": 3.80,
        "prior_close": 7100.0,
        "ma_10": 6820.0,
        "ma_20": 6540.0,
        "ma_50": 6180.0,
        "ma_100": None,
        "ma_200": None,
        "ma_dist_10": 1.04,
        "ma_dist_20": 2.08,
        "ma_dist_50": 3.41,
        "ma_dist_100": None,
        "ma_dist_200": None,
        "stack_state": None,
        "prior_move_21d": 14.20,
        "prior_move_63d": 26.90,
        "prior_move_126d": None,
        "pct_off_52w_high": None,
        "rs_63d": 21.40,
        "volume_ratio": 2.60,
        "avg_turnover_20d": 184_000_000_000.0,
        "stop_distance_adr": 1.24,
        "chased": None,
        "regime_at_entry": "uptrend",
        "regime_at_exit": "neutral",
        "benchmark": "^JKSE",
        "adr_pct_at_exit": 4.10,
        "ma_dist_10_at_exit": 1.61,
        "ma_dist_20_at_exit": 3.02,
        "ma_dist_50_at_exit": 5.10,
        "ma_dist_100_at_exit": None,
        "ma_dist_200_at_exit": None,
        "stack_state_at_exit": None,
        "rs_63d_at_exit": 24.80,
        "mfe_high": 8050.0,
        "mfe_date": "2026-07-22",
        "mae_low": 7010.0,
        "mae_date": "2026-07-09",
        "fwd_return_20d": None,
        "fwd_close_20d": None,
        "fwd_high": None,
        "fwd_high_date": None,
        "fwd_low": None,
        "fwd_low_date": None,
        "exits": [
            {
                "date": "2026-07-24",
                "quantity": 40_000,
                "price": 7815.0,
                "reason": "close_below_ma10",
                "mfe_high": 8050.0,
                "mfe_date": "2026-07-22",
                "mae_low": 7010.0,
                "mae_date": "2026-07-09",
            }
        ],
        "ruleset_version": "v1",
        "nominal_variant": "trail_ma10__partial_day3",
        "partial_state": "missed",
        "partial_timing_delta": None,
        "trail_exit_delta": 0,
        "deviation_cost_price": -140.0,
        "best_fit_variant": "trail_ma10__partial_none",
        "variants": [
            {"variant": "trail_ma10__partial_day3", "outcome": "resolved", "exit_price": 7675.0, "r": 1.28, "fit_distance_days": 3},
            {"variant": "trail_ma10__partial_day5", "outcome": "resolved", "exit_price": 7720.0, "r": 1.41, "fit_distance_days": 2},
            {"variant": "trail_ma10__partial_none", "outcome": "resolved", "exit_price": 7815.0, "r": 1.69, "fit_distance_days": 0},
            {"variant": "trail_ma20__partial_day3", "outcome": "capped", "exit_price": None, "r": None, "fit_distance_days": None},
            {"variant": "trail_ma20__partial_day5", "outcome": "capped", "exit_price": None, "r": None, "fit_distance_days": None},
            {"variant": "trail_ma20__partial_none", "outcome": "capped", "exit_price": None, "r": None, "fit_distance_days": None},
        ],
        "exit_note": "No stop written down at the time — reconstructed from where I remember putting it, under the 6900 shelf.",
        "bar_source": "yfinance",
        "fetch_date": "2026-08-11",
        "drift": None,
        "insufficient_history": ["ma_100", "ma_200", "stack_state", "pct_off_52w_high", "prior_move_126d"],
    },
]
