#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Scope: the IBKR half of issue #19. The Stockbit half is already settled —
# see docs/samples/equity-sources-findings.md — because the monthly Statement
# of Account is a PDF already in hand and could be read directly. The IBKR
# half needs a NEW Flex Query built in the portal, which only the account
# owner can do. That is what this wizard is for.
#
# What this wizard must NOT do, and why:
#   - It must not touch the existing Executions query (#2). That query feeds
#     the trades job; this is a SECOND, independent query.
#   - It must not press Generate on the Flex token. Generating a new token
#     silently invalidates the current one and would kill the trades job.
#     The existing token is reused from the vault.
VAULT="${VAULT:-$HOME/trading-journal-samples}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_SAMPLES="$REPO_ROOT/docs/samples"
ANSWERS="$REPO_SAMPLES/ibkr-nav-flex-findings.md"
ENV_FILE="$VAULT/.env"

mkdir -p "$VAULT" "$REPO_SAMPLES"
chmod 700 "$VAULT"

record() { printf '\n### %s\n\n%s\n' "$1" "${2:-_(not answered)_}" >> "$ANSWERS"; }

banner "IBKR NAV Flex query (issue #19)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — reuse the existing token, do not mint a new one"
say "Issue #15 concluded that IBKR account equity is derivable from a second"
say "Flex query carrying the NAV Summary section. That conclusion rests on an"
say "INFERENCE from IBKR's docs, whose prose describes the PDF layout and reads"
say "as denying a daily series. This wizard settles it against real data."
printf '\n'
missing=0
for t in curl python3; do
  if command -v "$t" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$t"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$t"; missing=1
  fi
done
(( missing )) && { warn "install the missing tools first"; exit 1; }
printf '\n'

if [[ -f "$ENV_FILE" ]] && grep -q '^IBKR_FLEX_TOKEN=' "$ENV_FILE"; then
  printf '  %s✓%s reusing the Flex token already in %s\n' "$GREEN" "$RESET" "$ENV_FILE"
  # shellcheck disable=SC1090
  set -a; . "$ENV_FILE"; set +a
else
  warn "no Flex token in $ENV_FILE — run scripts/sample-exports-wizard.sh first."
  warn "Do NOT mint a fresh token just for this: it would invalidate the one"
  warn "the trades job is using."
  exit 1
fi
printf '\n'
note "raw NAV statement → $VAULT (outside the repo, chmod 700)"
note "redacted findings → $ANSWERS (committed)"

{ printf '# IBKR NAV Flex — verification findings\n\n'
  printf 'Answers to the IBKR half of [#19](https://github.com/ajitimur/automatic-trading-journal/issues/19).\n'
  printf 'Produced by `scripts/equity-nav-wizard.sh` on %s.\n' "$(date +%Y-%m-%d)"
  printf '\nThe raw NAV statement is deliberately NOT in this repo — it is a year of\n'
  printf 'real account balances. Only redacted findings belong here.\n'
} > "$ANSWERS"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Build a SECOND Activity Flex Query — NAV only"
open_url "https://www.interactivebrokers.com/sso/Login?action=RM_STATEMENTS"
printf '\n'
warn "Do NOT open or edit the existing Executions query (id ${IBKR_QUERY_ID:-?})."
warn "Create a NEW one. Two queries, two ids, separate blast radius."
printf '\n'
step "Performance & Reports → Flex Queries → Activity Flex Query → +"
step "Add ONLY the section: Net Asset Value (NAV) Summary in Base."
step "Fields: Account ID, Report Date, Total, Cash, Stock."
printf '\n'
note "The XML element is <EquitySummaryByReportDateInBase>. Note that"
note "'Equity Summary in Base' names no section in the portal — #15 flagged"
note "that term as a false negative waiting to happen."
note "'netLiquidation' does not exist in Flex; the denominator field is 'total'."
printf '\n'
step "Period: Last N Calendar Days. Set N as high as the form will accept,"
step "  aiming for ~420 so we can see whether it clamps at 365."
step "Format: XML. Save it, then copy the new Query ID."
printf '\n'
note "While you are on that screen — this is the question #2 left open:"
ask NAV_PERIOD_OFFERED "What did the period control actually accept for N? (e.g. '420 accepted', 'clamped to 365', 'presets only'):"
ask NAV_QUERY_ID "Paste the NEW Flex Query ID (NAV):"
write_env NAV_QUERY_ID "$NAV_QUERY_ID"
record "What period does the NAV query accept?" "$NAV_PERIOD_OFFERED"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Fetch the NAV statement"
say "SendRequest, then GetStatement at whatever host the response names."
printf '\n'
NAV_XML="$VAULT/ibkr-nav.xml"

# The ISP intercepts DNS for interactivebrokers.com and answers with a block
# page address, so TLS fails and curl returns an EMPTY body — which looks
# nothing like a Flex error. Resolve over encrypted DNS instead, fresh every
# run: the Akamai edge rotates, and so does the ISP's block address (#2 saw
# 114.7.173.x; #19 saw 202.169.44.80). Never hardcode either.
#
# Resolve PER HOST, not once: SendRequest lives on ndcdyn but the response
# points GetStatement at gdcdyn, and both are intercepted.
doh_resolve() {
  curl -sS -m 15 -H 'accept: application/dns-json' \
    "https://1.1.1.1/dns-query?name=$1&type=A" 2>/dev/null \
    | python3 -c 'import json,sys
try: d = json.load(sys.stdin)
except Exception: sys.exit()
for a in d.get("Answer", []):
    if a.get("type") == 1:
        print(a["data"]); break' 2>/dev/null || true
}

# flex_get <full-url> <q-value> [curl args...]
flex_get() {
  local url="$1" qv="$2"; shift 2
  local host resolved args=()
  host="${url#https://}"; host="${host%%/*}"
  resolved="$(doh_resolve "$host")"
  if [[ -n "$resolved" ]]; then
    args=(--resolve "$host:443:$resolved")
    local sys; sys="$(dig +short "$host" 2>/dev/null | head -n1 || true)"
    if [[ -n "$sys" && "$sys" != "$resolved" ]]; then
      warn "$host: your DNS says $sys, real address is $resolved — ISP is"
      warn "  intercepting. Working around it."
    fi
  else
    note "encrypted DNS unavailable for $host; using system DNS"
  fi
  curl -sS -m 90 "${args[@]+"${args[@]}"}" --get "$url" \
    --data-urlencode "t=$IBKR_FLEX_TOKEN" \
    --data-urlencode "q=$qv" \
    --data-urlencode "v=3" "$@"
}

SEND_URL="https://ndcdyn.interactivebrokers.com/AccountManagement/FlexWebService/SendRequest"
resp="$(flex_get "$SEND_URL" "$NAV_QUERY_ID" || true)"
refcode="$(printf '%s' "$resp" | sed -n 's:.*<ReferenceCode>\(.*\)</ReferenceCode>.*:\1:p')"
geturl="$(printf '%s' "$resp" | sed -n 's:.*<Url>\(.*\)</Url>.*:\1:p')"
geturl="${geturl:-https://gdcdyn.interactivebrokers.com/AccountManagement/FlexWebService/GetStatement}"

if [[ -z "$refcode" ]]; then
  warn "SendRequest returned no reference code. Response:"
  printf '\n%s%s%s\n\n' "$DIM" "${resp:-(empty)}" "$RESET"
  if [[ -z "${resp//[[:space:]]/}" ]]; then
    warn "EMPTY response — that is a NETWORK failure, not a token problem."
    note "Nothing reached IBKR. This is the DNS interception; check the VPN or"
    note "the DoH path above. It is a DIFFERENT branch from 1012/1015/1013."
  else
    note "1012 = expired · 1015 = invalid · 1013 = IP restriction · 1020 = bad request"
    note "Note the HTTP status was almost certainly 200 — read the BODY."
  fi
  exit 1
fi
printf '  %s✓%s reference code obtained (GetStatement host: %s)\n' \
  "$GREEN" "$RESET" "$(printf '%s' "$geturl" | sed 's|https://||; s|/.*||')"

for attempt in 1 2 3 4 5 6 7 8 9 10; do
  sleep 3
  flex_get "$geturl" "$refcode" -o "$NAV_XML" || true
  if grep -q "<FlexQueryResponse" "$NAV_XML" 2>/dev/null; then
    printf '  %s✓%s retrieved (%s bytes)\n' \
      "$GREEN" "$RESET" "$(wc -c < "$NAV_XML" | tr -d ' ')"
    break
  fi
  code="$(sed -n 's:.*<ErrorCode>\(.*\)</ErrorCode>.*:\1:p' "$NAV_XML" 2>/dev/null || true)"
  note "attempt $attempt — not ready yet${code:+ (code $code)}"
  case "$code" in
    1012|1015|1013) warn "hard failure (code $code) — needs the portal."; exit 1 ;;
  esac
done

grep -q "<FlexQueryResponse" "$NAV_XML" 2>/dev/null || {
  warn "statement never became ready. Re-run later; saved values are remembered."
  exit 1
}
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Probe the NAV series"
say "The four questions #19 asks, answered from the file itself."
printf '\n'
PROBE_TMP="$(mktemp)"
python3 - "$NAV_XML" <<'PY' | tee "$PROBE_TMP"
import sys, datetime as dt, xml.etree.ElementTree as ET
from collections import Counter
root = ET.parse(sys.argv[1]).getroot()
rows = [e for e in root.iter() if e.tag == "EquitySummaryByReportDateInBase"]
print(f"  <EquitySummaryByReportDateInBase> rows: {len(rows)}")
if not rows:
    print("  ! none found — check the section was actually added to the query")
    print("  ! tags present: " + ", ".join(sorted({e.tag for e in root.iter()})[:20]))
    raise SystemExit

dates = [r.get("reportDate") for r in rows if r.get("reportDate")]
uniq = sorted(set(dates))
print(f"  distinct reportDate values: {len(uniq)}")
print(f"  earliest: {uniq[0]}   latest: {uniq[-1]}")
dupes = [d for d, n in Counter(dates).items() if n > 1]
print(f"  duplicated dates: {len(dupes)}" + (f" e.g. {dupes[:3]}" if dupes else ""))

# Q1: is this a daily series, or only period start/end?
if len(uniq) <= 2:
    print("  => NOT a daily series: only period endpoints. #15's IBKR verdict")
    print("     degrades sharply and #16's shape changes.")
else:
    print("  => a genuine multi-row series, one row per report date.")

# Q2: gaps. Count weekdays in span vs rows present.
d0 = dt.datetime.strptime(uniq[0], "%Y%m%d").date()
d1 = dt.datetime.strptime(uniq[-1], "%Y%m%d").date()
span_days = (d1 - d0).days + 1
weekdays = sum(1 for i in range(span_days)
               if (d0 + dt.timedelta(days=i)).weekday() < 5)
print(f"  span {d0} .. {d1} = {span_days} calendar days, {weekdays} weekdays")
print(f"  rows present / weekdays in span: {len(uniq)} / {weekdays}"
      f"  ({100*len(uniq)/weekdays:.1f}%)")
have = set(uniq)
missing = [ (d0 + dt.timedelta(days=i)).strftime("%Y%m%d")
            for i in range(span_days)
            if (d0 + dt.timedelta(days=i)).weekday() < 5
            and (d0 + dt.timedelta(days=i)).strftime("%Y%m%d") not in have ]
print(f"  weekdays with no row: {len(missing)}"
      + (f" e.g. {missing[:5]}" if missing else "  (US holidays explain a handful)"))

# Q3: does N > 365 actually reach back further than a year?
print(f"  span in days: {span_days} — {'>365, so N>365 WORKS' if span_days > 366 else 'clamped at ~1 year'}")

# Q4: total ~= cash + stock?
checked = bad = 0
worst = (-1.0, None)
for r in rows:
    try:
        t = float(r.get("total")); c = float(r.get("cash") or 0); s = float(r.get("stock") or 0)
    except (TypeError, ValueError):
        continue
    checked += 1
    denom = abs(t) or 1.0
    rel = abs(t - (c + s)) / denom
    if rel > worst[0]:
        worst = (rel, r.get("reportDate"))
    if rel > 0.01:
        bad += 1
print(f"  total == cash + stock: checked {checked}, off by >1% on {bad}")
print(f"  worst relative gap {worst[0]*100:.4f}% on {worst[1]}")
if checked and bad == 0:
    print("  => 'total' behaves like net liquidation value. Safe as the denominator.")
else:
    print("  => 'total' does NOT reconcile to cash+stock everywhere — other asset")
    print("     classes or accruals are in play. Inspect before trusting it.")
PY
printf '\n'
PROBE="$(cat "$PROBE_TMP" 2>/dev/null || true)"; rm -f "$PROBE_TMP"
record "Probe output (balances not included — counts and ratios only)" \
        "\`\`\`
$(printf '%s' "$PROBE" | sed -E 's/-?[0-9]{7,}(\.[0-9]+)?/<AMT>/g')
\`\`\`"
ask NAV_DAILY "One row per trading day, or only period endpoints? (daily/endpoints):"
ask NAV_REACH "Earliest reportDate actually returned — does it clear July 2026?:"
ask NAV_TOTAL "Does 'total' reconcile to cash+stock? (yes/no/mostly):"
record "Is the NAV section a daily series?" "$NAV_DAILY"
record "How far back does it reach?" "$NAV_REACH"
record "Does 'total' behave like net liquidation value?" "$NAV_TOTAL"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Confirm the error shape, then land"
say "An unattended job must never read a Flex error as 'no equity'. #19"
say "verified this AFK already; this re-confirms it against YOUR query id."
printf '\n'
bad="$(flex_get "$SEND_URL" "$NAV_QUERY_ID" -w '\nHTTP_STATUS=%{http_code}\n' \
        --data-urlencode "t=000000000000000000000000" || true)"
printf '%s\n' "$bad" | sed 's/^/  /'
printf '\n'
warn "If that shows HTTP_STATUS=200 with a <Status>Fail</Status> body, then"
warn "status-code checking alone is blind to it. The client MUST parse the body."
printf '\n'
record "Error shape on a deliberately bad token" \
       "$(printf '%s' "$bad" | sed -E 's/-?[0-9]{7,}/<REDACTED>/g')"
say "The raw NAV statement stays in the vault; it is a year of real balances."
printf '\n'
warn "Before committing $ANSWERS, eyeball it for balances and the account id."
open_url "file://$REPO_SAMPLES"
if confirm "Does it look clean of account numbers and balances?"; then
  say "Good. Commit it and comment the findings on issue #19."
else
  warn "Not clean — fix it by hand before committing."
fi
printf '\n'
note "  gh issue comment 19 --body-file $ANSWERS"

finish
