#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Scope: the IBKR half of issue #2. The Stockbit half is already settled —
# see docs/samples/export-findings.md — because its Trade Confirmation arrives
# as an email attachment and could be read directly. IBKR's daily email is a
# notification with no attachment, so its sample needs portal work only the
# account owner can do. That is what this wizard is for.
#
# VAULT holds the RAW statement and the live Flex token: never the repo.
# REPO_SAMPLES holds only redacted derivatives, per #2's redaction requirement.
VAULT="${VAULT:-$HOME/trading-journal-samples}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_SAMPLES="$REPO_ROOT/docs/samples"
ANSWERS="$REPO_SAMPLES/ibkr-flex-findings.md"
ENV_FILE="$VAULT/.env"

mkdir -p "$VAULT" "$REPO_SAMPLES"
chmod 700 "$VAULT"

record() { printf '\n### %s\n\n%s\n' "$1" "${2:-_(not answered)_}" >> "$ANSWERS"; }

banner "IBKR sample trade export (issue #2)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "This collects one real Flex statement and answers the items that"
say "docs/research/ibkr-trade-export.md marked UNVERIFIED."
printf '\n'
missing=0
for t in curl python3; do
  if command -v "$t" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$t"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$t"; missing=1
  fi
done
(( missing )) && { warn "install the missing tools first"; exit 1; }
printf '\n'
note "raw statement + token → $VAULT (outside the repo, chmod 700)"
note "redacted XML + notes  → $REPO_SAMPLES (committed)"
printf '\n'
say "Your IBKR account id is used only to scrub it back out of the sample."
ask IBKR_ACCOUNT "IBKR account id (e.g. U1234567):"
write_env IBKR_ACCOUNT "$IBKR_ACCOUNT"

{ printf '# IBKR Flex — sample findings\n\n'
  printf 'Empirical answers to the open items in `docs/research/ibkr-trade-export.md`.\n'
  printf 'Produced by `scripts/sample-exports-wizard.sh` on %s.\n' "$(date +%Y-%m-%d)"
  printf '\nThe raw Flex statement is deliberately NOT in this repo.\n'
} > "$ANSWERS"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Build the Activity Flex Query"
say "The daily IBKR email is a notification only — it carries no attachment."
say "Trade data has to come from a saved Flex Query."
open_url "https://www.interactivebrokers.com/sso/Login?action=RM_STATEMENTS"
step "Performance & Reports → Flex Queries → Activity Flex Query → +"
step "Add the TRADES section. Then, critically:"
printf '\n'
warn "Level of Detail = Executions   (anything else aggregates away the fills)"
warn "Tick 'Include Audit Trail fields' — otherwise Order Reference, Brokerage"
warn "  Order ID and Order Placement Time are silently absent"
printf '\n'
step "Include at least: Trade ID, IB Order ID, IB Execution ID, Trade Date,"
step "  Trade Time, Buy/Sell, Quantity, Trade Price, IB Commission, Currency,"
step "  Symbol, Asset Class, Level of Detail, Open/Close Indicator,"
step "  Original Trade ID, Change in Price, Change in Quantity."
step "Period: Last 365 Calendar Days.   Format: XML."
step "Save it, then copy the Query ID from the list."
printf '\n'
note "While you are on that screen — open item 5:"
ask IBKR_CUSTOM_RANGE "Does the period dropdown offer an arbitrary custom date range? (yes/no):"
ask IBKR_QUERY_ID "Paste the Flex Query ID:"
write_env IBKR_QUERY_ID "$IBKR_QUERY_ID"
record "Does Flex offer a custom date range beyond the presets? (open item 5)" \
       "$IBKR_CUSTOM_RANGE"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Enable Flex Web Service and mint a token"
open_url "https://www.interactivebrokers.com/sso/Login?action=RM_STATEMENTS"
step "Performance & Reports → Flex Queries → Flex Web Service Configuration."
printf '\n'
warn "The token defaults to SIX HOURS. A daily job dies on its second run."
warn "Set 'Should Expire After' to the longest option offered."
printf '\n'
note "Open item 2 asks what that dropdown actually offers — read it:"
ask IBKR_EXPIRY_OPTIONS "Durations listed in 'Should Expire After' (comma-separated):"
ask IBKR_EXPIRY_CHOSEN  "Which did you pick, and what date does it expire?:"
printf '\n'
step "Leave 'Valid For IP Address' BLANK — hosting is still undecided (#1), and"
step "  an IP-pinned token breaks with error 1013 the moment the job moves host."
step "Generate the token and copy it."
warn "Generating a new token invalidates the previous one."
ask_secret IBKR_FLEX_TOKEN "Paste the Flex token:"
write_env IBKR_FLEX_TOKEN "$IBKR_FLEX_TOKEN"
record "'Should Expire After' options (open item 2)" \
       "Offered: $IBKR_EXPIRY_OPTIONS

Chosen: $IBKR_EXPIRY_CHOSEN

Expiry surfaces as error 1012, which the daily job must escalate, not retry."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Fetch the statement"
say "Two GETs: SendRequest, then poll GetStatement until the report is built."
printf '\n'
FLEX_HOST="ndcdyn.interactivebrokers.com"
FLEX_BASE="https://$FLEX_HOST/AccountManagement/FlexWebService"
IBKR_XML="$VAULT/ibkr-flex.xml"

# Some Indonesian ISPs (Telkom/IndiHome among them) intercept DNS for
# interactivebrokers.com and answer with their own block-page address —
# 114.7.173.x rather than IBKR's Akamai edge. The TLS handshake then fails and
# curl returns an EMPTY body, which looks nothing like a token problem and sent
# the first run of this wizard down the wrong path entirely.
#
# So: resolve the host over encrypted DNS (which the ISP cannot rewrite) and
# pin that address with --resolve. Looked up fresh each run because the Akamai
# edge address rotates — never hardcode it.
FLEX_RESOLVE=()
resolved="$(curl -sS -m 15 -H 'accept: application/dns-json' \
            "https://1.1.1.1/dns-query?name=$FLEX_HOST&type=A" 2>/dev/null \
            | python3 -c 'import json,sys
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit()
for a in d.get("Answer", []):
    if a.get("type") == 1:
        print(a["data"]); break' 2>/dev/null || true)"

if [[ -n "$resolved" ]]; then
  local_dns="$(dig +short "$FLEX_HOST" 2>/dev/null | head -n1 || true)"
  FLEX_RESOLVE=(--resolve "$FLEX_HOST:443:$resolved")
  if [[ -n "$local_dns" && "$local_dns" != "$resolved" ]]; then
    warn "your DNS answers $local_dns for $FLEX_HOST, but the real address is"
    warn "$resolved — your ISP is intercepting it. Working around it."
  else
    note "resolved $FLEX_HOST → $resolved"
  fi
else
  note "encrypted DNS lookup unavailable; using system DNS"
fi

flex_get() {  # flex_get <endpoint> <q-value> [-o outfile]
  local ep="$1" qv="$2"; shift 2
  curl -sS -m 90 "${FLEX_RESOLVE[@]+"${FLEX_RESOLVE[@]}"}" --get "$FLEX_BASE/$ep" \
    --data-urlencode "t=$IBKR_FLEX_TOKEN" \
    --data-urlencode "q=$qv" \
    --data-urlencode "v=3" "$@"
}

resp="$(flex_get SendRequest "$IBKR_QUERY_ID" || true)"
refcode="$(printf '%s' "$resp" | sed -n 's:.*<ReferenceCode>\(.*\)</ReferenceCode>.*:\1:p')"

if [[ -z "$refcode" ]]; then
  warn "SendRequest returned no reference code. Response:"
  printf '\n%s%s%s\n\n' "$DIM" "${resp:-(empty)}" "$RESET"
  if [[ -z "${resp//[[:space:]]/}" ]]; then
    warn "The response was EMPTY — that is a NETWORK problem, not your token."
    note "Nothing reached IBKR. Check whether you are on a VPN, or whether your"
    note "ISP is still intercepting DNS for $FLEX_HOST."
  else
    note "1012 = token expired · 1015 = token invalid · 1013 = IP restriction"
    note "1020 = invalid request (usually a wrong query id or token)"
    note "Fix it in the portal and re-run — entered values are remembered."
  fi
  exit 1
fi
printf '  %s✓%s reference code obtained\n' "$GREEN" "$RESET"

for attempt in 1 2 3 4 5 6 7 8 9 10; do
  sleep 3
  flex_get GetStatement "$refcode" -o "$IBKR_XML" || true
  if grep -q "<FlexQueryResponse" "$IBKR_XML" 2>/dev/null; then
    printf '  %s✓%s retrieved (%s bytes)\n' \
      "$GREEN" "$RESET" "$(wc -c < "$IBKR_XML" | tr -d ' ')"
    break
  fi
  code="$(sed -n 's:.*<ErrorCode>\(.*\)</ErrorCode>.*:\1:p' "$IBKR_XML" 2>/dev/null || true)"
  note "attempt $attempt — not ready yet${code:+ (code $code)}"
  case "$code" in
    1012|1015|1013)
      warn "hard failure (code $code) — needs the portal, not a retry."; exit 1 ;;
  esac
done

grep -q "<FlexQueryResponse" "$IBKR_XML" 2>/dev/null || {
  warn "statement never became ready. Securities settle after ~20:20 EST —"
  warn "try again this evening. Re-running keeps your saved values."
  exit 1
}
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Probe the XML"
say "Answering open items 1 and 3, and testing the commission claim from §5.1."
printf '\n'
python3 - "$IBKR_XML" <<'PY'
import re, sys, xml.etree.ElementTree as ET
from collections import Counter, defaultdict
root = ET.parse(sys.argv[1]).getroot()
trades = [e for e in root.iter() if e.tag in ("Trade", "TradeConfirm")]
print(f"  trade rows: {len(trades)}")
if not trades:
    print("  ⚠ no trades in this window — widen the query period and re-run")
    raise SystemExit
lod = Counter(t.get("levelOfDetail", "?") for t in trades)
print(f"  levelOfDetail values: {dict(lod)}")
if len(lod) > 1:
    print("  ⚠ multiple levels in one file — the importer MUST filter on this")
for a in ("dateTime", "tradeDate", "tradeTime", "orderTime"):
    vals = {t.get(a) for t in trades if t.get(a)}
    if vals:
        print(f"  {a}: e.g. {sorted(vals)[0]!r}")
tz = {t.get("tradeTimeZone") or t.get("timeZone") for t in trades}
tz.discard(None)
print(f"  explicit timezone attribute: {tz or 'NONE — still unresolved'}")
ids = [i for i in (t.get("ibExecID") or t.get("execID") or "" for t in trades) if i]
print(f"  exec ids: {len(ids)}, matching <base>.<seq>: "
      f"{sum(1 for i in ids if re.search(r'[.]\d+$', i))}")
if ids:
    print(f"  sample exec id: {ids[0]!r}")
byorder = defaultdict(list)
for t in trades:
    byorder[t.get("ibOrderID")].append(t)
multi = {k: v for k, v in byorder.items() if len(v) > 1}
print(f"  orders with >1 fill: {len(multi)}")
for _, v in list(multi.items())[:3]:
    comms = [t.get("ibCommission") for t in v]
    nz = sum(1 for c in comms if c and float(c) != 0)
    print(f"    {len(v)} fills → commissions {comms} ({nz} non-zero)")
PY
printf '\n'
say "Compare those timestamps against a trade whose time you actually know."
ask IBKR_TZ    "Timezone of IBKR trade timestamps? (or 'still unknown'):"
ask IBKR_EXECID "Do exec ids look like <base>.<seq>? (yes/no/unclear):"
ask IBKR_COMM  "Commission on the FIRST fill only? (yes/no/no multi-fill sample):"
record "Timezone of trade timestamps (open item 1)" "$IBKR_TZ"
record "Exec id format (open item 3)" "$IBKR_EXECID"
record "Commission on first fill only (confirms §5.1)" \
       "$IBKR_COMM — if yes, commission is an ORDER-level field, never per-fill.
This matches Stockbit, where cost attaches at the day+side level. Both brokers
put cost above the fill; see docs/samples/export-findings.md."
note "Open item 4 (id stability across reruns) needs a SECOND run on another"
note "day — save this XML, re-run, and diff the ids."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Redact and land"
say "The raw statement stays in the vault. Only a redacted copy is committed."
printf '\n'
python3 - "$IBKR_XML" "$REPO_SAMPLES/ibkr-flex-sample.xml" "$IBKR_ACCOUNT" <<'PY'
import re, sys, xml.etree.ElementTree as ET
src, dst, acct = sys.argv[1], sys.argv[2], sys.argv[3].strip()
tree = ET.parse(src); root = tree.getroot()
DROP = {"accountId", "acctAlias", "clientAccountID", "accountAlias"}
for el in root.iter():
    for k in list(el.attrib):
        if k in DROP:
            el.set(k, "REDACTED")
tree.write(dst, encoding="utf-8", xml_declaration=True)
t = open(dst, encoding="utf-8").read()
if acct:
    t = t.replace(acct, "U-REDACTED")
t = re.sub(r"\bU\d{6,}\b", "U-REDACTED", t)
open(dst, "w", encoding="utf-8").write(t)
print("  ✓ wrote redacted XML")
PY
printf '\n'
warn "Automated redaction is a first pass, not a guarantee. Eyeball it —"
warn "balances and any account alias in particular — before committing."
open_url "file://$REPO_SAMPLES"
if confirm "Does it look clean of account numbers and balances?"; then
  say "Good. Commit $REPO_SAMPLES and comment the findings on issue #2."
else
  warn "Not clean — fix it by hand in $REPO_SAMPLES before committing."
fi
printf '\n'
note "  gh issue comment 2 --body-file $ANSWERS"

finish
